name: Shell Commands 

on:
  schedule:
    - cron: "0/5 * * * *"
    
  pull_request:
    types:
      - "closed"
      - "assigned"
      - "opened"
      - "reopened"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: multiline script 
        run: |
           node -v 
           npm -v
  win-shell-command:
    runs-on: ubuntu-latest
    needs: ['run-shell-command']
    steps: 
      - name: multiline script 
        run: |
           node -v 
           npm -v

  linux-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: multiline script 
        id: dip
        uses: actions/javascript-action@v1
        with:
         milliseconds: 1000
         
      - name: checkout
        uses: actions/checkout@v1

      - name: Log dipendra time
        run: echo "${{steps.dip.outputs.time}}"
